- README.md
Method only takes a single parameter (see actual code sample)
> Fixing AppDelegate code snippet

- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.Droid/packages.config
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.nuget.props
- UserDetailsClient/UserDetailsClient.UWP/project.json
- UserDetailsClient/UserDetailsClient.UWP/project.lock.json
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
- UserDetailsClient/UserDetailsClient.iOS/packages.config
- UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj
- UserDetailsClient/UserDetailsClient/packages.config
Reverts Azure-Samples/active-directory-b2c-xamarin-native#51
Getting an exception on iOS
> Revert "Updating to MSAL 1.1.3-preview and Xamarin.Android.Support to 27.0.2 …"

- UserDetailsClient/UserDetailsClient.Droid/Resources/Resource.Designer.cs
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.Droid/packages.config
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.nuget.props
- UserDetailsClient/UserDetailsClient.UWP/project.json
- UserDetailsClient/UserDetailsClient.UWP/project.lock.json
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
- UserDetailsClient/UserDetailsClient.iOS/packages.config
- UserDetailsClient/UserDetailsClient/UserDetailsClient.csproj
- UserDetailsClient/UserDetailsClient/packages.config
Manually tested w/Android device (Plus One), iOS simulator and UWP
> update to MSAL 1.1.4-preview

- UserDetailsClient/UserDetailsClient.iOS/Entitlements.plist
#55 
@bgavrilMS - I had issues w/MSBuild but things build fine in VS. MSBuild complained about issues with the resources in Android project. LMK if you have similar issues.
> Enable keychain in Entitlements.plist file

- UserDetailsClient/UserDetailsClient.Core/App.cs
- UserDetailsClient/UserDetailsClient.Core/MainPage.xaml.cs
- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/MainActivity.cs
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.Droid/packages.config
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/AppDelegate.cs
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
- UserDetailsClient/UserDetailsClient.iOS/packages.config
Update to MSAL.NET 3.0.4 which has not yet released
(here taken from myget)
> Update to MSAL.NET 3.0.4

- UserDetailsClient/UserDetailsClient.Core/App.xaml
- UserDetailsClient/UserDetailsClient.Core/App.xaml.cs
- UserDetailsClient/UserDetailsClient.Core/Features/LogOn/B2CAuthenticationService.cs
- UserDetailsClient/UserDetailsClient.Core/Features/LogOn/B2CConstants.cs
- UserDetailsClient/UserDetailsClient.Core/Features/LogOn/IAuthenticationService.cs
- UserDetailsClient/UserDetailsClient.Core/Features/LogOn/UserContext.cs
- UserDetailsClient/UserDetailsClient.Core/MainPage.xaml
- UserDetailsClient/UserDetailsClient.Core/MainPage.xaml.cs
- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/MainActivity.cs
- UserDetailsClient/UserDetailsClient.Droid/Properties/AndroidManifest.xml
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.Droid/packages.config
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/AppDelegate.cs
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
- UserDetailsClient/UserDetailsClient.iOS/packages.config
i needed to manually change the path to the Microsoft.Identity.Client to Monodroid90 instead of .net standard 1.3
> upgraded to 3.0.8

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.Droid/packages.config
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
- UserDetailsClient/UserDetailsClient.iOS/packages.config
> update to msal 4.0

- UserDetailsClient/UserDetailsClient.Core/App.xaml.cs
- UserDetailsClient/UserDetailsClient.Core/Features/LogOn/B2CAuthenticationService.cs
- UserDetailsClient/UserDetailsClient.Core/Features/LogOn/B2CConstants.cs
- UserDetailsClient/UserDetailsClient.Core/Features/LogOn/IAuthenticationService.cs
- UserDetailsClient/UserDetailsClient.Core/Features/LogOn/UserContext.cs
- UserDetailsClient/UserDetailsClient.Core/MainPage.xaml
- UserDetailsClient/UserDetailsClient.Core/MainPage.xaml.cs
- UserDetailsClient/UserDetailsClient.Droid/MainActivity.cs
- UserDetailsClient/UserDetailsClient.iOS/AppDelegate.cs
> fixing up a few things

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.Droid/packages.config
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
- UserDetailsClient/UserDetailsClient.iOS/packages.config
@jmprieur so...this sample worked w/the api call as well. it wasn't the other day or for the past several weeks.
> update to msal 4.6

- README.md
- UserDetailsClient/UserDetailsClient.Droid/MsalActivity.cs
- UserDetailsClient/UserDetailsClient.Droid/Properties/AndroidManifest.xml
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.Droid/packages.config
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
- UserDetailsClient/UserDetailsClient.iOS/packages.config
Included MsalActivity as a replacement of the changes in the manifest.
Updated README.md
> Adding Activity in code

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/Resources/Resource.Designer.cs
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.Droid/packages.config
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/packages.config
> Update to MSAL 4.13.0

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.Droid/packages.config
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/packages.config
Reverts Azure-Samples/active-directory-b2c-xamarin-native#126 as it was pushed by accident
> Revert "Update to MSAL 4.13.0"

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.Droid/packages.config
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/packages.config
recreating PR for @aiwangmicrosoft 
https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/pull/126
> Update to MSAL 4.13

- README.md
fix for https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/125
> Update android specific steps

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/Resources/Resource.Designer.cs
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.Droid/packages.config
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
- UserDetailsClient/UserDetailsClient.iOS/packages.config
- active-directory-b2c-Xamarin-native.sln
i thought we were already on android x, but i had a lot of updates. not sure how we want to do this PR, but it builds and works for me... @jmprieur
> update to msal4.22

- UserDetailsClient/UserDetailsClient.Droid/Properties/AndroidManifest.xml
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
Tested and works out of the box
> Adding support for Android 11

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/Properties/AndroidManifest.xml
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
> Trwalke/msal 4.29 update

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
PR to update MSAL to 4.32.0.
Tested
> Updating MSAL to 4.32.0

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
> Upgrade to MSAL 4.36.0

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
> Update to 4.36.2

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
> Update to MSAL 4.40.0

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
> Update to MSAL 4.41.0

- UserDetailsClient/UserDetailsClient.Core/UserDetailsClient.Core.csproj
- UserDetailsClient/UserDetailsClient.Droid/UserDetailsClient.Droid.csproj
- UserDetailsClient/UserDetailsClient.UWP/UserDetailsClient.UWP.csproj
- UserDetailsClient/UserDetailsClient.iOS/UserDetailsClient.iOS.csproj
> Update to MSAL 4.42.0
